config/routes.rb
Tkiero::Application.routes.draw do
  get "users/new"

  get "signup" => "users#new", :as => "signup"
  resources :users

  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"
  resources :sessions, only: [:new, :create, :destroy]

  root to: 'static_pages#home'

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id             :integer         not null, primary key
#  name           :string(255)
#  email          :string(255)
#  password_hash  :string(255)
#  password_salt  :string(255)
#  created_at     :datetime        not null
#  updated_at     :datetime        not null
#  auth_token     :string(255)
#  remember_token :string(255)
#

class User < ActiveRecord::Base
    #only allow access to this fields from the internet 
    attr_accessible :name, :email, :password, :password_confirmation

    # Creates an instance variable for :password submitted by the HTML Form, and validate password_confirmation 
    attr_accessor :password
    validates_confirmation_of :password
    
    #Calls encrypt_password method to encrypt before saving the user model    
    before_save :encrypt_password
    before_save :create_remember_token

    # Downloadcase before save email to avoid possible eMail duplication issues   
    # before_save { |user| user.email = email.downcase }
    before_create :downcase_eMail

    
    #Validation policy for users: name, password and eMail
    validates :name, presence: true, 
                     length: { minimum: 1, maximum: 50 }
    
    validates :password, presence: true,
                          :on => :create,
                          length: { minimum: 6, maximum: 100 }

    
    #validates_presence_of :email
    #validates_uniqueness_of :email
    #TODO - Must improve the validating eMail Regex for 'oli.@gmail..com'
    validates :email, presence: true, 
                      length: { minimum: 3, maximum: 100 },
                      #format: { with: /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i },
                      format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                      #uniqueness: true
                      uniqueness: { case_sensitive: false }
  
    # Creates a remember_token for cookie validation

    # Method to download case of eMail before create model method 
    #private
    def downcase_eMail
      self.email.downcase!
    end
    
  
    # Method to Authenticate users on controller 
    def self.authenticate(email, password)
      user = find_by_email(email)
      if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
        user 
      else
        nil
      end
    end
    
    # Method to encrypt users' passwords creating two db fields: pw_salt & pw_hash  
    def encrypt_password
      if password.present?
        self.password_salt = BCrypt::Engine.generate_salt
        self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
      end
    end
    
    private
    
      def create_remember_token
        self.remember_token = SecureRandom.urlsafe_base64
      end
      
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
  
  # RAILS CASTS 250 
  # helper_method :current_user
  #
  # private
  #
  # def current_user
    # @current_user ||= User.find(session[:user_id]) if session[:user_id]
  # end
  
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      #Sign-In Function
      sign_in user

      # Redirects to the user Wall page page when loged in
      #redirect_to user, :notice => "Logged In, Welcome to tKiero App !!!"
      redirect_to user
            
      #RAILS CASTS 250
      #session[:user_id] = user.id
      
      # Redirects to the root page
      #redirect_to root_url, :notice => "Logged In, Welcome to tKiero App !!!"
      
    else
      flash.now.alert = "Invalid eMail or Password"
      render "new"
    end
  end
  
  def destroy
    sign_out
    #redirect_to root_url, :notice => "Logged Out !!!"
    redirect_to root_url
    
    #RAILS CASTS 250
    #session[:user_id] = nil
    #redirect_to root_url, :notice => "Logged Out !!!"
  end
  
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  #Static Page of the site - HOME
  def home
    if signed_in?
         @user = current_user
    end
  end

  #Static Page of the site - HELP
  def help
  end

  #Static Page of the site - ABOUT
  def about
  end

  #Static Page of the site - ABOUT
  def contact
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # this controller handles user sing-up, sing-in and log-off, as well as all validations
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save 
      sign_in @user
      flash[:success] = "You have succesfully created your account, Welcome to tKiero App !!!"
      redirect_to @user
      #redirect_to root_url, :notice => "Signup !!!"
    else
      render 'new'
    end
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      # Handle Valid update
      flash[:success] = "Profile Updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "tKiero Demo App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
  
end

app/helpers/sessions_helper.rb
module SessionsHelper

  #Writes user remember_token on user's lcoal cookie
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    current_user = user
    #Using cookies.permanent causes Rails to set the expiration to 20.years.from_now automatically.
  end
  
  def signed_in?
    !current_user.nil?
  end

  # Signs out the user cookies to remove the remember token from the session
  def sign_out
    current_user = nil
    cookies.delete(:remember_token)
  end
  
  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  # def gravatar_for(user)
    # gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    # gravatar_url = "http://gravatar.com/avatar/#{gravatar_id}"
    # image_tag(gravatar_url, alt: user.name, class: "gravatar")
  # end
 def gravatar_for(user, options = { size: 35 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
 end
end

app/views/layouts/_footer.html.erb
<footer>
	<div class="container">
		<!-- MyFooter row of 4 columns -->
		<div class="row">
			<div class="span8"> 
				<!-- 12 columns -->
				<div class="row">
					<div class="span2">
						<h4>About us</h4>
						<span class="label success">New</span>
						<li><%= link_to "About Us", about_path %></li>
						<li><a href="#">Company</a></li>

<!--
						<a href="#">Team & Mentors & Board</a>
						<br>
						<a href="#">Customer Stories</a>
						<br>
						<a href="#">Jobs</a>
						<br>
						<a href="#">Press</a>
						<br>
						<a href="#">Copyright Policy</a>
						<br>
						<br>
						<p>Donec id elit non mi porta gravida at eget metus.</p>
-->
					</div> <!-- /SPAN2 -->
					<div class="span2">
						<h4>Legal info</h4>
						<li><%= link_to "Contact Us", contact_path %></li>
						<li><a href="#">Legal Info</a></li>
						<li><a href="#">Terms of Use & Service</a></li>
						<li><a href="#">Privacy Policy </a></li>
						<li><a href="#">Copyright Policy</a></li>
						<br>
						<br>
						<p>Donec id elit non mi porta gravida at eget metus.</p>
					</div> <!-- /SPAN2 -->
					<div class="span2">
						<h4>Our Products</h4>
						<li><%= link_to "AAA & BBB", "http://www.buildoneideas.com" %></li>
						<br>
<!--
						<a href='http://www.buildoneideas.com'>CCC</a>
						<br>
						<a href='http://www.buildoneideas.com'>DDD</a>
						<br>
						<br>
						<p>Donec id elit non mi porta gravida at eget metus.</p>
-->
					</div> <!-- /SPAN2 -->
				</div>	<!-- 12 columns -->	
			</div>
			<div class="span pull-right">
				<h4>Stay in Touch</h4>
				<a href='http://www.twitter.com'>
				<img src="http://github.com/intridea/authbuttons/raw/master/png/twitter_32.png" alt="Twitter">
				</a>
				<a href='http://www.facebook.com'>
				<img src="http://github.com/intridea/authbuttons/raw/master/png/facebook_32.png" alt="Facebook">
				</a>
				<a href='http://plus.google.com'>
				<img src="http://github.com/intridea/authbuttons/raw/master/png/google_32.png" alt="Google+">
				</a>
				<br>
			</div> <!-- /SPAN2 -->
			<div class="span12 center"
				<br>
				<br>
				<br>
				<p>&copy; 2011-2012 All Rights Reserved. <a href='http://www.buildoneideas.com'>&reg;BuildOneIDeas</a> is a registered trademark of SETI Desarrollo Tecnologico S.L.</p>
				<%= link_to image_tag("b1IDeasLogo60x60.png", alt: "Build One IDeas"), 'http://www.buildoneideas.com/' %>
			</div>
		</div> <!-- /row 12 = 3 + 9 -->
	</div> <!-- /footer -->
</footer>

app/views/layouts/_header.html.erb
	<!-- NavBar
	-------------------------------------------------- -->
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
        	  <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" id="logo" href="<%= root_path %>">tKiero</a>
		  <!-- #<%= link_to "tKiero Demo App", '#', id: "logo" %> -->
          <div class="nav-collapse">
            <ul class="nav pull-right">
              <li class="active">
				<a href="<%= root_path %>"><i class="icon-home icon-white"></i> Home</a>
              </li>              
              <% if signed_in? %>
	            <li> <%= link_to "Users", '#' %> </li>
	            <li id="fat-menu" class="dropdown">
	              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
	                <!-- Account -->
	                <% if @user %> 
	                		<i> <%= gravatar_for @user %> </i>
	                	<% else %>
	                		Account 
	                	<% end %>
	                <b class="caret"></b> 
	              </a>
	              <ul class="dropdown-menu">
	                <% if @user %> 
						<li>
							<b> <%= @user.name %>  </b><br/ >
							<%= @user.email %>
						</li>
	                	<% end %>
					<li class="divider"></li>
	                <li><%= link_to "My Wall", current_user %></li>
	                <li><%= link_to "My Settings", edit_user_path(current_user) %></li>
		            <li><%= link_to "Help", help_path %></li>
	                <li class="divider"></li>
	                <li>
	                  <%= link_to "Log Out", logout_path %>
	                </li>
	              </ul>
	            </li>
	          <% else %>
	            <li><%= link_to "Log In", login_path %></li>
	          <% end %>
              
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>

	<!-- Fix for Mobile Devices -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<%= render 'layouts/shim' %>    
	<!-- Le fav icon -->
    <link rel="shortcut icon" href="<%= asset_path "favicon.ico" %>">
  </head>
  <body>
    <%= render 'layouts/header' %>    
    <div class="container">
    	
    		<!-- Div for Flash Messages-->    		
    		<% if flash.first %>
			<div class="alert alert-success">
	  			<button class="close" data-dismiss="alert">×</button>
		    		<!-- Displays all flash messages of the main app-->
		    		<% flash.each do |key, value| %>
		    			<%= content_tag :div, value, :id => "flash_#{key}" %>
			        <!-- or class: "alert alert-#{key}" -->
		    		<% end %>
	    		</div>
    		<% end %>

    		<%= yield %>
    </div>
    <br>
    <br>
    <br>
    <br>
    <%= render 'layouts/footer' %>
	<% if Rails.env.development? %>
		<div class="alert alert-info">
	  		<button class="close" data-dismiss="alert">×</button>
	  		<%= debug(params) if Rails.env.development? %>		
		</div>
	<% end %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<!-- Displays errors of the form, if any on -->
<% if @user.errors.any? %>
	<div class="alert alert-error pull-left">
		<button class="close" data-dismiss="alert">×</button>		    		
		<p>The form contains <%= pluralize(@user.errors.count, "error") %></p>
		<ul>
		    <% @user.errors.full_messages.each do |message| %>
				<li>	<%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>

<h1>tKiero App</h1>
<p>
	This is Our Team, the crazy ones who think theycan change the world.
	We belive that there is a lot to disconver. Together. That's why we love to help people to bring their ideas to life.
	This is what we do in <a href="http://www.buildoneideas.com"> Build One IDeas</a>
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>tKiero App</h1>
<p>
	This is the Contact Page of  
	<a href="http://www.buildoneideas.com"> Build One IDeas</a>
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>tKiero App</h1>
<p>
	If you need help with our site you can contact us at. 
	<a href="http://www.buildoneideas.com"> Build One IDeas</a>
</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>

<!-- Hero-Unit Call To Action
-------------------------------------------------- -->
<div class="center hero-unit">
	<!-- MAIN CALL TO ACTION -->
	<h1>tKiero App</h1>
  	<h2>Si quieres algo, dilo bien alto !!!</h2>
	<p>This is the Home Page for one of the New Labs of 
    	<a href="http://www.buildoneideas.com"> Build One IDeas</a></p>
	<%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-success" %>	
</div>
	
<br>
	
<!-- 3 Column 'Hero Page' row
-------------------------------------------------- -->
<div class="row calltoaction">
    <div class="span4">
    		<h2>Lo Kieres</h2>
		<p>Añade a la lista de tus sueños todo lo que quieras que te regalen o que quieres comprarte, cuando se te ocurra, donde se te ocurra, de la forma más fácil...</p>
    		<p><a class="pull-right btn" href="#">Ver detalles &raquo;</a></p>
		<!-- ><p><a class="btn btn-primary btn-large">Learn more »</a></p> -->
    </div>
    <div class="span4">
    		<h2>Lo Kompartes</h2>
    		<p>
    			Ordena tu lista y prioriza lo que quieres y quien te lo puede regalar.
    			Comparte tu lista con los que te kieren y pide un deseo !!! 
    		</p>
    		<p><a class="pull-right btn" href="#">Ver detalles &raquo;</a></p>
   </div>
    <div class="span4">
    		<h2>....y Konsigues tus sueños</h2>
    		<p>
    			Portate bien, sé bueno y konsigue tus sueños
    		</p>
    		<p><a class="pull-right btn" href="#">Ver detalles &raquo;</a></p>
    </div>
</div>
<!-- Line Break Separator -->	
<hr>


<!-- Carousel
-------------------------------------------------- -->

<div class="container">  <!-- MyFooter row of 4 columns -->
	<div class="row">
		<div class="span12">  <!-- 12 columns -->
			<div class="row-fluid">
				<div class="span">  <!-- 12 columns -->
					<!-- Carousel -->
					<div id="myCarousel" class="carousel">     <!-- Carousel items -->
						<div class="carousel-inner">
					  		<div class="active item"><img src="<%= asset_path "kierelo.png" %>" alt>
					    			<div class="carousel-caption">
					    				<h4>Añade</h4>
					    				<p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
					    			</div>
					    		</div>
					  		<div class="item"><img src="<%= asset_path "kompartelo.png" %>" alt>
					    			<div class="carousel-caption">
					    				<h4>Ordena</h4>
					    				<p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
					    			</div>
					    		</div>
					  		<div class="item"><img src="<%= asset_path "konsiguelo.png" %>" alt>
					    			<div class="carousel-caption">
					    				<h4>Comparte</h4>
					    				<p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
						    		</div>
					    		</div>
					  	</div>
					  	<!-- Carousel nav -->
					  	<a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
					  	<a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/users/edit.html.erb
<!-- Sign Up page -->
<% provide(:title, 'Edit User') %>


<div class="center hero-unit">
	<!-- Sign Up Form -->
	<h2>tKiero App - Update Your User Profile Settings</h2>
	<p>
		Change your account details
	</p><br />

	<%= form_for @user do |f| %>
		<!-- Displays errors of the form, if any on -->
		  <%= render 'shared/error_messages' %>
		<br />
		<div class="row">
  			<div class="span6">
				<p>
					<%= f.label :name %>
					<%= f.text_field :name, :placeholder => "name", autofocus:"true" %>
				</p>
				<p>
					<%= f.label :email %>
					<%= f.text_field :email, :placeholder => "eMail"  %>
				</p>
				<p>
					<%= f.label :password %>
					<%= f.password_field :password, :placeholder =>'password' %>
				</p>
				<p>
					<%= f.label :password_confirmation %>
					<%= f.password_field :password_confirmation, :placeholder =>'confirm password'%>
				</p>
				<br />
				<p><%= f.submit "Save Changes", class:"btn btn-large btn-success" %></p>
			</div>
			<div class="span3">
    				<a href="http://gravatar.com/emails">Change your Gravatar Image</a>
				<%= gravatar_for @user %>
			</div>
		</div>
	<% end %>
	<br />			
	<p>...ot if you already have an account, login here</p>
	<%= link_to "Log In here", login_path, class: "btn btn-large btn-success" %>

</div>

app/views/users/new.html.erb
<!-- Sign Up page -->
<% provide(:title, 'Sign Up') %>


<div class="center hero-unit">
	<!-- Sign Up Form -->
	<h2>tKiero App - Sign Up</h2>
	<p>
		Please fill in the form with to create a new account for tKiero App
		<br />
		tKiero App is one of current Build One IDeas Lab projects
	</p><br />

	<%= form_for @user do |f| %>
		<!-- Displays errors of the form, if any on -->
		  <%= render 'shared/error_messages' %>
		<br />
		<div class="row">
  			<div class="span6">
				<p>
					<%= f.label :name %>
					<%= f.text_field :name, :placeholder => "name", autofocus:"true" %>
				</p>
				<p>
					<%= f.label :email %>
					<%= f.text_field :email, :placeholder => "eMail"  %>
				</p>
				<p>
					<%= f.label :password %>
					<%= f.password_field :password, :placeholder =>'password' %>
				</p>
				<p>
					<%= f.label :password_confirmation %>
					<%= f.password_field :password_confirmation, :placeholder =>'confirm password'%>
				</p>
				<br />
				<p><%= f.submit "Create your Account", class:"btn btn-large btn-success" %></p>
			</div>
			<div class="span4">
				<img src="http://placehold.it/350x330" alt="attention catching logo goes here">
			</div>
		</div>
	<% end %>
	<br />			
	<p>...ot if you already have an account, login here</p>
	<%= link_to "Log In here", login_path, class: "btn btn-large btn-success" %>

</div>
    

app/views/users/show.html.erb
<!-- Show User  Page -->
<% provide(:title, @user.name) %>

<h1>tKiero App</h1>
<div class="row">
  <aside class="span4">
    <section>
      <h2>
        <%= gravatar_for @user %>
        <%= @user.name %> <br/ >
		<%= @user.email %>
      </h2>
    </section>
  </aside>
</div>



<br/ >
<p class="center">
	This is Page is part of one of the Labs ob   
	<a href="http://www.buildoneideas.com"> Build One IDeas</a>
</p>